# Generated by Django 5.0.4 on 2024-04-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chair', models.PositiveIntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'chair',
            },
        ),
    ]
